baseURL = "https://litspacehome.netlify.app"
languageCode = "en-us"
paginate = 6
theme = "portio-hugo"
title = "Nova W.S."
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Service"
url = "#service"
weight = 3
[[menu.main]]
name = "Work"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 5
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 6
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4
[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright Â© Portio 2020"
footerLogo = "/images/logo.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "/images/logo.png"
[params.address]
address = "Based out of the United States"
email = "robertstrey@hotmail.com"
openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "+(972)358-5686"
[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/"
weight = 1
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
